server:
  port: 8082
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/gestientPatient
    username: root
    password: root2022
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
